name: Lancer tests unitaires

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
       # 1. Checkout
      - name: 1. Checkout...
        uses: actions/checkout@v3

      # 2. Set up
      - name: 2. Set up .NET...
        uses : actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.0'
      
      # 3. Build
      - name: 3. Build...
        run: dotnet build --configuration Release

      # 4. Unit tests
      - name: 4. Unit tests...
        run: dotnet test
  
