name: Lancer tests unitaires

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
       # 1. Checkout
      - name: 1. Checkout...
        uses: actions/checkout@v4

      # 2. Set up
      - name: 2. Set up .NET...
        uses : actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # 3. Restore Dependencies
      - name: 3. Restore Dependencies...
        run: dotnet restore 14E_TP2_A23/14E_TP2_A23.csproj
      
      # 4. Build
      - name: 4. Build...
        run: dotnet build 14E_TP2_A23/14E_TP2_A23.csproj

      # 5. Unit tests
      - name: 5. Unit tests...
        run: dotnet test 14E_TP2_A23_Tests/14E_TP2_A23_Tests.csproj
  
